/**
 * beeEye.js – 3-D bee compound-eye renderer.
 *
 * Adapts Andy Giger's B-EYE algorithm for a true 3-D environment.
 *
 *  • Each ommatidium has a fixed angular position (ax, ay) relative to the
 *    bee head, generated by CreateOmm (unchanged from the original).
 *  • Each (ax, ay) is converted to a 3-D direction vector on the head sphere.
 *  • Per frame, the scene is rendered into 6 perspective views (+X, -X, +Y,
 *    -Y, +Z, -Z) centred on the bee head, each into its own 2-D render
 *    target.  This is the same idea as a cubemap but with full per-face
 *    control over FOV and up-vector — Three.js's built-in CubeCamera uses a
 *    negative FOV and per-face flipped up-vectors that make raw-byte readback
 *    almost impossible to interpret correctly.
 *  • For each ommatidium we rotate its sample directions by the bee's head
 *    yaw, pick the face the direction lands in, and project onto that face's
 *    own basis vectors to get a pixel coordinate.
 *  • The Gaussian acceptance kernel (CreateGaussLow) is applied as small
 *    angular perturbations of the sample direction.
 *  • Hexagonal mosaic display (DispHex) is unchanged in algorithm.
 *
 * Original Processing source: Processing_OmmatidiaView_R001_10.pde
 */

import * as THREE from 'three';

// ── Parameters ───────────────────────────────────────────────────────────────
const FACE_SIZE  = 128;                        // pixels per face render target
const DR         = 2.6 / 180 * Math.PI;        // delta-rho — Laughlin & Horridge 1972
const BGR        = [0, 120, 40];               // colour returned for samples that miss
const EMPTY_CELL = [12, 12, 12];               // wabe cells with no ommatidium → near-black
const NEAR       = 0.1;
const FAR        = 800;

// ── Per-face camera setup ────────────────────────────────────────────────────
// Each face has a forward direction and an up vector.  Using lookAt(forward)
// with cam.up = up_input gives us the camera's world-space basis as:
//   backward = -forward
//   right    = up_input × backward
//   up_act   = backward × right
// We pre-compute (right, up_act, forward) so sampling is a few dot products.
// (right, up_act are recomputed below to make sure the math is internally
// consistent rather than trusted from a paper derivation.)
const FACE_DEFS = [
  // [ index, forward,                up                ]
  { fwd: [+1,  0,  0], up: [ 0, +1,  0] }, // 0: +X
  { fwd: [-1,  0,  0], up: [ 0, +1,  0] }, // 1: -X
  { fwd: [ 0, +1,  0], up: [ 0,  0, +1] }, // 2: +Y (looking up)
  { fwd: [ 0, -1,  0], up: [ 0,  0, -1] }, // 3: -Y (looking down)
  { fwd: [ 0,  0, +1], up: [ 0, +1,  0] }, // 4: +Z
  { fwd: [ 0,  0, -1], up: [ 0, +1,  0] }, // 5: -Z
];

// Compute (right, up_actual, forward) basis for each face — these match the
// world-space orientation Three.js will produce when we call lookAt(forward)
// with cam.up = up_input.  Three.js: right = up × backward = up × (-forward).
function buildFaceBases() {
  return FACE_DEFS.map(({ fwd, up }) => {
    const f = fwd, u = up;
    const b = [-f[0], -f[1], -f[2]]; // backward
    // right = up × backward
    const r = [
      u[1] * b[2] - u[2] * b[1],
      u[2] * b[0] - u[0] * b[2],
      u[0] * b[1] - u[1] * b[0],
    ];
    // up_actual = backward × right
    const ua = [
      b[1] * r[2] - b[2] * r[1],
      b[2] * r[0] - b[0] * r[2],
      b[0] * r[1] - b[1] * r[0],
    ];
    return { fwd: f, right: r, up: ua };
  });
}

const FACE_BASES = buildFaceBases();

export class BeeEyeRenderer {
  constructor() {
    this.omm   = [];
    this.nromm = 0;
    this.gau   = [];
    this.gsp   = 0;

    this._buildOmmatidia();
    this._buildGauss();

    // 6 face cameras + 6 render targets + 6 CPU pixel buffers
    this.faceCams    = [];
    this.faceTargets = [];
    this.facePixels  = [];
    const faceBytes  = FACE_SIZE * FACE_SIZE * 4;
    for (let i = 0; i < 6; i++) {
      // Positive 90° FOV — no Three.js CubeCamera trickery
      const cam = new THREE.PerspectiveCamera(90, 1, NEAR, FAR);
      this.faceCams.push(cam);
      this.faceTargets.push(new THREE.WebGLRenderTarget(FACE_SIZE, FACE_SIZE, {
        format:          THREE.RGBAFormat,
        type:            THREE.UnsignedByteType,
        generateMipmaps: false,
        minFilter:       THREE.LinearFilter,
        magFilter:       THREE.LinearFilter,
      }));
      this.facePixels.push(new Uint8Array(faceBytes));
    }

    // Reusable target vector for lookAt
    this._tmpTarget = new THREE.Vector3();

    // Output 2-D canvas (set later via setCanvas)
    this.canvas = null;
    this.ctx    = null;

    // Pre-compute head-local sample directions for every ommatidium
    this._precomputeSampleDirs();
  }

  // ── CreateOmm: direct port from Processing ────────────────────────────────
  _buildOmmatidia() {
    const dphmin = 0.0489, dphmax = 0.0646;
    const dpvmin = 0.0262, dpvmax = 0.0611;
    let x = 0, y = 0;
    let oddy = false;
    let i = 0;
    while (y < 1.57) {
      while (x < 1.57) {
        this.omm[i]   = { x:  x, y:  y, r: BGR[0], g: BGR[1], b: BGR[2] };
        this.omm[i+1] = { x: -x, y:  y, r: BGR[0], g: BGR[1], b: BGR[2] };
        this.omm[i+2] = { x:  x, y: -y, r: BGR[0], g: BGR[1], b: BGR[2] };
        this.omm[i+3] = { x: -x, y: -y, r: BGR[0], g: BGR[1], b: BGR[2] };
        i += 4;
        const wg = dphmin + Math.abs((x - 0.7854) * ((dphmax - dphmin) / 0.7854));
        const x2 = Math.sin(wg / 2) / Math.cos(y);
        x = x2 <= 1 ? x + Math.asin(x2) * 2 : 1.57;
      }
      y += (dpvmin + y * ((dpvmax - dpvmin) / 1.5708)) / 2;
      if (!oddy && y < 1.57) {
        const x2 = Math.sin(dphmax / 2) / Math.cos(y);
        x = x2 <= 1 ? Math.asin(x2) : 1.57;
        oddy = true;
      } else {
        x = 0; oddy = false;
      }
    }
    this.nromm = Math.max(0, i - 4);
  }

  // ── CreateGaussLow: direct port ───────────────────────────────────────────
  _buildGauss() {
    this.gau[0] = { x: 0, y: 0, g: 0.10225 };
    this.gsp = 1;
    for (let i = 1; i <= 2; i++) {
      const k = i * 8;
      const g = 0.10225 * Math.exp(-0.6932 * Math.pow(i * 3 / 4.0, 2));
      for (let j = 0; j < k; j++) {
        this.gau[this.gsp++] = {
          x: (i * 3 / 4.0) * Math.sin(6.2832 / k * j),
          y: (i * 3 / 4.0) * Math.cos(6.2832 / k * j),
          g,
        };
      }
    }
  }

  /**
   * For every ommatidium, pre-compute the gsp 3-D sample direction vectors
   * in head-local space (forward = -Z, right = +X, up = +Y).  Each Gaussian
   * offset is a fraction of an ommatidium width = DR radians.
   */
  _precomputeSampleDirs() {
    const N = this.nromm;
    const G = this.gsp;
    const dirs    = new Float32Array(N * G * 3);
    const weights = new Float32Array(N * G);

    for (let i = 0; i < N; i++) {
      const ax = this.omm[i].x;
      const ay = this.omm[i].y;
      for (let j = 0; j < G; j++) {
        const sax = ax + this.gau[j].x * DR;
        const say = ay + this.gau[j].y * DR;

        const cy = Math.cos(say);
        const dx =  cy * Math.sin(sax);
        const dy =  Math.sin(say);
        const dz = -cy * Math.cos(sax);

        const base = i * G * 3 + j * 3;
        dirs[base    ] = dx;
        dirs[base + 1] = dy;
        dirs[base + 2] = dz;
        weights[i * G + j] = this.gau[j].g;
      }
    }
    this.sampleDirs    = dirs;
    this.sampleWeights = weights;
  }

  // ── Attach output 2-D canvas ──────────────────────────────────────────────
  setCanvas(canvas) {
    if (this.canvas === canvas) return;
    this.canvas = canvas;
    this.ctx    = canvas.getContext('2d');
  }

  /**
   * Sample the 6-face render at a world-space direction.
   * Picks the face whose forward axis dominates, projects the direction onto
   * that face's (right, up, forward) basis, and reads the corresponding
   * pixel from that face's CPU buffer.
   */
  _sampleDirection(dx, dy, dz) {
    // Pick face by largest absolute component
    const ax = Math.abs(dx);
    const ay = Math.abs(dy);
    const az = Math.abs(dz);
    let face;
    if (ax >= ay && ax >= az) face = dx > 0 ? 0 : 1;
    else if (ay >= az)        face = dy > 0 ? 2 : 3;
    else                      face = dz > 0 ? 4 : 5;

    const basis = FACE_BASES[face];
    const fwd   = basis.fwd;
    const right = basis.right;
    const up    = basis.up;

    // Project direction onto camera basis
    const r_x = dx * right[0] + dy * right[1] + dz * right[2];
    const r_y = dx * up[0]    + dy * up[1]    + dz * up[2];
    const r_z = dx * fwd[0]   + dy * fwd[1]   + dz * fwd[2];
    if (r_z <= 1e-6) return BGR; // outside this face's frustum (shouldn't happen)

    // 90° FOV → focal length = halfSize (since tan(45°) = 1)
    const half = FACE_SIZE * 0.5;
    let px = Math.floor(half + (r_x / r_z) * half);
    // Framebuffer Y is bottom-up: positive r_y (image up) maps to higher index
    let py = Math.floor(half + (r_y / r_z) * half);

    if (px < 0) px = 0; else if (px >= FACE_SIZE) px = FACE_SIZE - 1;
    if (py < 0) py = 0; else if (py >= FACE_SIZE) py = FACE_SIZE - 1;

    const idx = (py * FACE_SIZE + px) * 4;
    const buf = this.facePixels[face];
    return [buf[idx], buf[idx + 1], buf[idx + 2]];
  }

  /**
   * Sample each ommatidium using precomputed head-local directions, rotated
   * by the bee's head yaw to world space (single Y-axis rotation).
   */
  _procPat(headYaw) {
    const cy = Math.cos(headYaw);
    const sy = Math.sin(headYaw);
    const N = this.nromm;
    const G = this.gsp;
    const dirs    = this.sampleDirs;
    const weights = this.sampleWeights;

    for (let i = 0; i < N; i++) {
      let cr = 0, cg = 0, cb = 0;
      const baseI = i * G;
      for (let j = 0; j < G; j++) {
        const di = baseI * 3 + j * 3;
        const lx = dirs[di    ];
        const ly = dirs[di + 1];
        const lz = dirs[di + 2];

        // Rotate around Y by headYaw
        const wx =  cy * lx + sy * lz;
        const wy =  ly;
        const wz = -sy * lx + cy * lz;

        const c = this._sampleDirection(wx, wy, wz);
        const g = weights[baseI + j];
        cr += c[0] * g;
        cg += c[1] * g;
        cb += c[2] * g;
      }
      this.omm[i].r = cr;
      this.omm[i].g = cg;
      this.omm[i].b = cb;
    }
  }

  // ── DispHex: hexagonal mosaic display ────────────────────────────────────
  // +y ommatidia (looking up in the world) draw towards the TOP of the canvas.
  _dispHex() {
    if (!this.ctx || !this.canvas) return;
    const W   = this.canvas.width;
    const H   = this.canvas.height;
    const ctx = this.ctx;

    // Near-black background — gaps read as inter-ommatidial dark space
    ctx.fillStyle = `rgb(${EMPTY_CELL[0]},${EMPTY_CELL[1]},${EMPTY_CELL[2]})`;
    ctx.fillRect(0, 0, W, H);

    const WABE_W = 60, WABE_H = 160;
    const wabe = new Array(WABE_W).fill(null).map(() =>
      new Array(WABE_H).fill(null).map(() => EMPTY_CELL.slice())
    );

    let wx = 0, wy = 0, odd = 0;
    for (let i = 0; i < this.nromm - 4; i += 4) {
      const row  = Math.min(WABE_H - 1, 80 + wy);
      const rowN = Math.max(0,           80 - wy);
      const colR = Math.min(WABE_W - 1, 30 + wx);
      const colL = Math.max(0,          30 - wx - odd);

      if (colR >= 0 && colR < WABE_W && row >= 0 && row < WABE_H)
        wabe[colR][row]  = [this.omm[i].r,   this.omm[i].g,   this.omm[i].b];
      if (colL >= 0 && colL < WABE_W && row >= 0 && row < WABE_H)
        wabe[colL][row]  = [this.omm[i+1].r, this.omm[i+1].g, this.omm[i+1].b];
      if (colR >= 0 && colR < WABE_W && rowN >= 0 && rowN < WABE_H)
        wabe[colR][rowN] = [this.omm[i+2].r, this.omm[i+2].g, this.omm[i+2].b];
      if (colL >= 0 && colL < WABE_W && rowN >= 0 && rowN < WABE_H)
        wabe[colL][rowN] = [this.omm[i+3].r, this.omm[i+3].g, this.omm[i+3].b];

      if (i + 4 < this.nromm && this.omm[i + 4].x < this.omm[i].x) {
        wx = 0; wy++;
        odd = odd === 1 ? 0 : 1;
      } else {
        wx++;
      }
    }

    const cellW = W / WABE_W;
    const cellH = H / WABE_H;
    // Hex radius — overlap neighbours so the mosaic reads as a continuous image
    const r = Math.max(cellW, cellH) * 0.85;

    // wabe[i][j]: j=80 is centre.  j > 80 = +y ommatidia (looking up) →
    // draw towards TOP of canvas.  Flip j → canvas Y so larger j = smaller y.
    for (let j = 0; j < WABE_H; j++) {
      const yPx  = (WABE_H - 1 - j) * cellH + cellH * 0.5;
      const offX = (j % 2 === 1) ? cellW * 0.5 : 0;
      for (let i = 0; i < WABE_W; i++) {
        const c = wabe[i][j];
        ctx.fillStyle = `rgb(${Math.round(c[0])},${Math.round(c[1])},${Math.round(c[2])})`;
        ctx.beginPath();
        ctx.arc(i * cellW + offX + cellW * 0.5, yPx, r, 0, Math.PI * 2);
        ctx.fill();
      }
    }
  }

  /**
   * Main render call (called from Viewport each frame).
   *
   * @param {THREE.WebGLRenderer} renderer
   * @param {THREE.Scene}         scene
   * @param {THREE.Vector3}       headPosition  – world-space bee head position
   * @param {number}              headYaw       – head yaw in radians (bodyYaw + headYaw)
   * @param {THREE.Object3D}      [beeMesh]     – hidden during render so the bee
   *                                              doesn't occlude its own view
   */
  render(renderer, scene, headPosition, headYaw, beeMesh) {
    if (!scene || !renderer || !headPosition) return;

    // 1. Hide bee model so we don't see its insides
    let prevVis = true;
    if (beeMesh) { prevVis = beeMesh.visible; beeMesh.visible = false; }

    // 2. Render scene to each of the 6 face render targets
    const prevTarget = renderer.getRenderTarget();
    for (let face = 0; face < 6; face++) {
      const cam = this.faceCams[face];
      const def = FACE_DEFS[face];
      cam.position.copy(headPosition);
      cam.up.set(def.up[0], def.up[1], def.up[2]);
      this._tmpTarget.set(
        headPosition.x + def.fwd[0],
        headPosition.y + def.fwd[1],
        headPosition.z + def.fwd[2],
      );
      cam.lookAt(this._tmpTarget);
      renderer.setRenderTarget(this.faceTargets[face]);
      renderer.render(scene, cam);
    }
    renderer.setRenderTarget(prevTarget);

    if (beeMesh) beeMesh.visible = prevVis;

    // 3. Read each face buffer back to CPU
    for (let face = 0; face < 6; face++) {
      renderer.readRenderTargetPixels(
        this.faceTargets[face], 0, 0, FACE_SIZE, FACE_SIZE,
        this.facePixels[face],
      );
    }

    // 4. Sample each ommatidium (rotate sample dirs by head yaw)
    this._procPat(headYaw);

    // 5. Draw the hex mosaic
    this._dispHex();
  }

  dispose() {
    for (const t of this.faceTargets) t.dispose();
  }
}
