/**
 * beeEye.js – 3-D bee compound-eye renderer (dual-eye, with binocular zone).
 *
 * Adapts Andy Giger's B-EYE algorithm for a true 3-D environment.
 *
 *  • Each ommatidium has a fixed angular position (ax, ay) relative to its
 *    own eye, generated by CreateOmm (unchanged from the original).
 *  • Two eye layouts (Left and Right) are produced from one ommatidium grid
 *    by tilting the eye-local directions by ±EYE_TILT_DEG around the head's
 *    Y axis.  The two eye hex mosaics are drawn side-by-side on the output
 *    canvas.
 *  • Per frame, the scene is rendered into 6 perspective views (+X, -X, +Y,
 *    -Y, +Z, -Z) centred on the bee head, each into its own 2-D render
 *    target.  Each face uses positive 90° FOV and a known up-vector — we
 *    avoid Three.js's CubeCamera which uses negative FOV and per-face
 *    flipped up-vectors that make raw-byte readback inconsistent.
 *  • For each ommatidium of each eye we rotate its sample directions by the
 *    bee's head yaw, pick the face the direction lands in, and project onto
 *    that face's basis vectors to get a pixel coordinate.
 *  • The Gaussian acceptance kernel (CreateGaussLow) is applied as small
 *    angular perturbations of the sample direction.
 *  • An ommatidium is flagged "binocular" if its head-local direction lies
 *    within BINOCULAR_HALF_ANGLE_DEG of head-forward — i.e. inside the
 *    overlapping field of view of both eyes.  A thin outline is drawn around
 *    binocular hexagons when showBinocular is true.
 *
 * Original Processing source: Processing_OmmatidiaView_R001_10.pde
 */

import * as THREE from 'three';

// ── Mobile detection ─────────────────────────────────────────────────────────
// Checked once at module load — drives performance trade-offs below.
const IS_MOBILE = typeof navigator !== 'undefined' &&
  (navigator.maxTouchPoints > 0 || /Mobi|Android|iPhone|iPad/i.test(navigator.userAgent));

// ── Parameters ───────────────────────────────────────────────────────────────
// On mobile we cut the face render target from 128→64 (4× fewer pixels to
// read back) and limit the Gaussian ring count to 1 (9 samples instead of 25).
// The bee-eye render is also throttled to every 3rd frame via _eyeFrameSkip.
const FACE_SIZE                = IS_MOBILE ? 64 : 128; // pixels per face render target
const GAUSS_RINGS              = IS_MOBILE ? 1  : 2;   // rings in CreateGaussLow (1→9 samples, 2→25)
const EYE_FRAME_SKIP           = IS_MOBILE ? 3  : 1;   // render bee-eye every Nth frame
const DR                       = 2.6 / 180 * Math.PI;  // delta-rho — Laughlin & Horridge 1972
const BGR                      = [0, 120, 40];         // colour returned for samples that miss
const EMPTY_CELL               = [12, 12, 12];         // wabe cells with no ommatidium
const NEAR                     = 0.1;
const FAR                      = 800;
const EYE_TILT_DEG             = 60;                   // outward yaw of each eye from head-forward
const BINOCULAR_HALF_ANGLE_DEG = 30;                   // half-width of binocular zone

// ── Per-face camera setup ────────────────────────────────────────────────────
// Each face: forward direction and up vector chosen so the math is internally
// consistent (no Three.js CubeCamera trickery).  For each face we precompute
// (right, up_actual, forward) basis in world coords.  Sampling = projecting
// the world-space sample direction onto these basis vectors.
const FACE_DEFS = [
  { fwd: [+1,  0,  0], up: [ 0, +1,  0] }, // 0: +X
  { fwd: [-1,  0,  0], up: [ 0, +1,  0] }, // 1: -X
  { fwd: [ 0, +1,  0], up: [ 0,  0, +1] }, // 2: +Y (looking up)
  { fwd: [ 0, -1,  0], up: [ 0,  0, -1] }, // 3: -Y (looking down)
  { fwd: [ 0,  0, +1], up: [ 0, +1,  0] }, // 4: +Z
  { fwd: [ 0,  0, -1], up: [ 0, +1,  0] }, // 5: -Z
];

// Three.js lookAt: right = up × backward, up_actual = backward × right
function buildFaceBases() {
  return FACE_DEFS.map(({ fwd, up }) => {
    const f = fwd, u = up;
    const b = [-f[0], -f[1], -f[2]];
    const r = [
      u[1] * b[2] - u[2] * b[1],
      u[2] * b[0] - u[0] * b[2],
      u[0] * b[1] - u[1] * b[0],
    ];
    const ua = [
      b[1] * r[2] - b[2] * r[1],
      b[2] * r[0] - b[0] * r[2],
      b[0] * r[1] - b[1] * r[0],
    ];
    return { fwd: f, right: r, up: ua };
  });
}

const FACE_BASES = buildFaceBases();

export class BeeEyeRenderer {
  constructor() {
    // Single ommatidium grid (eye-local angular coords) — both eyes use this
    this.omm   = [];
    this.nromm = 0;
    this.gau   = [];
    this.gsp   = 0;

    this._buildOmmatidia();
    this._buildGauss();

    // Two eye layouts.  In Three.js (right-handed, +Y up), rotating
    // forward (0,0,-1) by +60° around Y yields (-0.866, 0, -0.5) — i.e. the
    // bee's left.  So Left eye gets +tilt, Right eye gets -tilt.
    this.eyes = [
      this._buildEye(+EYE_TILT_DEG * Math.PI / 180),  // 0 = Left  (head's left)
      this._buildEye(-EYE_TILT_DEG * Math.PI / 180),  // 1 = Right (head's right)
    ];

    // 6 face cameras + 6 render targets + 6 CPU pixel buffers
    this.faceCams    = [];
    this.faceTargets = [];
    this.facePixels  = [];
    const faceBytes  = FACE_SIZE * FACE_SIZE * 4;
    for (let i = 0; i < 6; i++) {
      const cam = new THREE.PerspectiveCamera(90, 1, NEAR, FAR);
      this.faceCams.push(cam);
      const target = new THREE.WebGLRenderTarget(FACE_SIZE, FACE_SIZE, {
        format:          THREE.RGBAFormat,
        type:            THREE.UnsignedByteType,
        generateMipmaps: false,
        minFilter:       THREE.LinearFilter,
        magFilter:       THREE.LinearFilter,
      });
      // Encode the framebuffer as sRGB so raw-byte reads match what the
      // 1st-person canvas displays (Three.js default render targets are
      // linear, which reads back ~half as bright as the on-screen view).
      target.texture.colorSpace = THREE.SRGBColorSpace;
      this.faceTargets.push(target);
      this.facePixels.push(new Uint8Array(faceBytes));
    }

    this._tmpTarget = new THREE.Vector3();

    // Frame-skip counter for mobile throttling
    this._eyeFrameCounter = 0;

    // Output 2-D canvas (set later via setCanvas)
    this.canvas = null;
    this.ctx    = null;

    // User-tunable display options
    this.brightness     = 1.0;   // multiplied per-channel before display
    this.showBinocular  = true;  // draw outline on binocular ommatidia
  }

  // ── CreateOmm: direct port from Processing ────────────────────────────────
  _buildOmmatidia() {
    const dphmin = 0.0489, dphmax = 0.0646;
    const dpvmin = 0.0262, dpvmax = 0.0611;
    let x = 0, y = 0;
    let oddy = false;
    let i = 0;
    while (y < 1.57) {
      while (x < 1.57) {
        this.omm[i]   = { x:  x, y:  y };
        this.omm[i+1] = { x: -x, y:  y };
        this.omm[i+2] = { x:  x, y: -y };
        this.omm[i+3] = { x: -x, y: -y };
        i += 4;
        const wg = dphmin + Math.abs((x - 0.7854) * ((dphmax - dphmin) / 0.7854));
        const x2 = Math.sin(wg / 2) / Math.cos(y);
        x = x2 <= 1 ? x + Math.asin(x2) * 2 : 1.57;
      }
      y += (dpvmin + y * ((dpvmax - dpvmin) / 1.5708)) / 2;
      if (!oddy && y < 1.57) {
        const x2 = Math.sin(dphmax / 2) / Math.cos(y);
        x = x2 <= 1 ? Math.asin(x2) : 1.57;
        oddy = true;
      } else {
        x = 0; oddy = false;
      }
    }
    this.nromm = Math.max(0, i - 4);
  }

  // ── CreateGaussLow: direct port (GAUSS_RINGS controls how many rings) ─────
  // Rings=2 → 1 + 8 + 16 = 25 samples (desktop default)
  // Rings=1 → 1 + 8      =  9 samples (mobile, ~2.8× faster _procPat)
  _buildGauss() {
    this.gau[0] = { x: 0, y: 0, g: 0.10225 };
    this.gsp = 1;
    for (let i = 1; i <= GAUSS_RINGS; i++) {
      const k = i * 8;
      const g = 0.10225 * Math.exp(-0.6932 * Math.pow(i * 3 / 4.0, 2));
      for (let j = 0; j < k; j++) {
        this.gau[this.gsp++] = {
          x: (i * 3 / 4.0) * Math.sin(6.2832 / k * j),
          y: (i * 3 / 4.0) * Math.cos(6.2832 / k * j),
          g,
        };
      }
    }
  }

  /**
   * Build one eye's per-ommatidium data.  The eye is yaw-tilted by `tiltY`
   * (radians, around the Y axis) — left eye = -tilt, right eye = +tilt.
   *
   * For each ommatidium:
   *   • Pre-compute the gsp head-local sample direction vectors with the
   *     Gaussian offsets already baked in.  The eye-local direction
   *     (sin(ax)cos(ay), sin(ay), -cos(ay)cos(ax)) is then yaw-rotated by
   *     tiltY to get head-local.
   *   • Compute the binocular flag: head-local direction within
   *     BINOCULAR_HALF_ANGLE_DEG of head-forward (0,0,-1).
   *   • Allocate an r/g/b colour, initially BGR.
   */
  _buildEye(tiltY) {
    const N = this.nromm;
    const G = this.gsp;
    const cosT = Math.cos(tiltY);
    const sinT = Math.sin(tiltY);
    const dirs    = new Float32Array(N * G * 3);
    const weights = new Float32Array(N * G);
    const binocular = new Uint8Array(N);
    const colours = new Array(N);
    const cosBino = Math.cos(BINOCULAR_HALF_ANGLE_DEG * Math.PI / 180);

    for (let i = 0; i < N; i++) {
      const ax = this.omm[i].x;
      const ay = this.omm[i].y;

      // Centre direction in head-local space — used for the binocular check.
      // (Gaussian samples will be very close to this.)
      const cy0 = Math.cos(ay);
      const eldX =  cy0 * Math.sin(ax);
      const eldY =  Math.sin(ay);
      const eldZ = -cy0 * Math.cos(ax);
      // Yaw-rotate by tiltY around Y axis: head-local direction
      const hldX =  cosT * eldX + sinT * eldZ;
      const hldY =  eldY;
      const hldZ = -sinT * eldX + cosT * eldZ;
      // Binocular if within half-angle of head-forward (0, 0, -1)
      const dotForward = -hldZ;
      binocular[i] = dotForward > cosBino ? 1 : 0;

      colours[i] = { r: BGR[0], g: BGR[1], b: BGR[2] };

      // Gaussian sample directions (head-local space)
      for (let j = 0; j < G; j++) {
        const sax = ax + this.gau[j].x * DR;
        const say = ay + this.gau[j].y * DR;
        const cy  = Math.cos(say);
        const elx =  cy * Math.sin(sax);
        const ely =  Math.sin(say);
        const elz = -cy * Math.cos(sax);
        // Apply eye yaw tilt → head-local
        const hlx =  cosT * elx + sinT * elz;
        const hly =  ely;
        const hlz = -sinT * elx + cosT * elz;

        const base = i * G * 3 + j * 3;
        dirs[base    ] = hlx;
        dirs[base + 1] = hly;
        dirs[base + 2] = hlz;
        weights[i * G + j] = this.gau[j].g;
      }
    }

    return { dirs, weights, binocular, colours };
  }

  // ── Public setters ────────────────────────────────────────────────────────
  setBrightness(b) {
    if (typeof b === 'number' && isFinite(b)) {
      this.brightness = Math.max(0, Math.min(8, b));
    }
  }
  setShowBinocular(flag) { this.showBinocular = !!flag; }

  // ── Attach output 2-D canvas ──────────────────────────────────────────────
  setCanvas(canvas) {
    if (this.canvas === canvas) return;
    this.canvas = canvas;
    this.ctx    = canvas.getContext('2d');
  }

  /**
   * Sample the 6-face render at a world-space direction.
   * Picks the face whose forward axis dominates, projects the direction onto
   * that face's (right, up, forward) basis, and reads from that face's CPU
   * pixel buffer.  Framebuffer is bottom-up: positive image-up (+r_y) maps
   * to a higher pixel index, which is the top of the rendered image.
   */
  _sampleDirection(dx, dy, dz) {
    const ax = Math.abs(dx);
    const ay = Math.abs(dy);
    const az = Math.abs(dz);
    let face;
    if (ax >= ay && ax >= az) face = dx > 0 ? 0 : 1;
    else if (ay >= az)        face = dy > 0 ? 2 : 3;
    else                      face = dz > 0 ? 4 : 5;

    const basis = FACE_BASES[face];
    const fwd = basis.fwd, right = basis.right, up = basis.up;

    const r_x = dx * right[0] + dy * right[1] + dz * right[2];
    const r_y = dx * up[0]    + dy * up[1]    + dz * up[2];
    const r_z = dx * fwd[0]   + dy * fwd[1]   + dz * fwd[2];
    if (r_z <= 1e-6) return BGR;

    const half = FACE_SIZE * 0.5;
    let px = Math.floor(half + (r_x / r_z) * half);
    let py = Math.floor(half + (r_y / r_z) * half);
    if (px < 0) px = 0; else if (px >= FACE_SIZE) px = FACE_SIZE - 1;
    if (py < 0) py = 0; else if (py >= FACE_SIZE) py = FACE_SIZE - 1;

    const idx = (py * FACE_SIZE + px) * 4;
    const buf = this.facePixels[face];
    return [buf[idx], buf[idx + 1], buf[idx + 2]];
  }

  /**
   * Sample one eye's ommatidia.  Sample directions are precomputed in
   * head-local space (with eye tilt baked in); we apply head yaw here.
   */
  _procPatEye(eye, headYaw) {
    const cy = Math.cos(headYaw);
    const sy = Math.sin(headYaw);
    const N = this.nromm;
    const G = this.gsp;
    const dirs    = eye.dirs;
    const weights = eye.weights;
    const colours = eye.colours;

    for (let i = 0; i < N; i++) {
      let cr = 0, cg = 0, cb = 0;
      const baseI = i * G;
      for (let j = 0; j < G; j++) {
        const di = baseI * 3 + j * 3;
        const lx = dirs[di    ];
        const ly = dirs[di + 1];
        const lz = dirs[di + 2];

        // Rotate around Y by headYaw (head-local → world)
        const wx =  cy * lx + sy * lz;
        const wy =  ly;
        const wz = -sy * lx + cy * lz;

        const c = this._sampleDirection(wx, wy, wz);
        const g = weights[baseI + j];
        cr += c[0] * g;
        cg += c[1] * g;
        cb += c[2] * g;
      }
      const o = colours[i];
      o.r = cr;
      o.g = cg;
      o.b = cb;
    }
  }

  /**
   * Build a wabe colour grid for one eye's ommatidia.  Returns a
   * WABE_W × WABE_H grid where each cell is either an [r, g, b] colour or
   * null (no ommatidium covers this cell).  We keep null vs. coloured cells
   * separate so unfilled cells stay near-black instead of being painted as
   * a green hex around the eye image.
   *
   * Also returns a parallel `binoMask` grid: true if the cell is filled by
   * a binocular ommatidium.
   */
  _buildWabe(eye, WABE_W, WABE_H) {
    const wabe = new Array(WABE_W);
    const binoMask = new Array(WABE_W);
    for (let i = 0; i < WABE_W; i++) {
      wabe[i]     = new Array(WABE_H).fill(null);
      binoMask[i] = new Array(WABE_H).fill(false);
    }

    const colours    = eye.colours;
    const binocular  = eye.binocular;
    const cx = WABE_W >> 1;  // 30
    const cy = WABE_H >> 1;  // 80

    let wx = 0, wy = 0, odd = 0;
    for (let i = 0; i < this.nromm - 4; i += 4) {
      const row  = Math.min(WABE_H - 1, cy + wy);
      const rowN = Math.max(0,           cy - wy);
      const colR = Math.min(WABE_W - 1, cx + wx);
      const colL = Math.max(0,          cx - wx - odd);

      const c0 = colours[i],   b0 = binocular[i];
      const c1 = colours[i+1], b1 = binocular[i+1];
      const c2 = colours[i+2], b2 = binocular[i+2];
      const c3 = colours[i+3], b3 = binocular[i+3];

      if (colR >= 0 && colR < WABE_W && row >= 0 && row < WABE_H) {
        wabe[colR][row]     = [c0.r, c0.g, c0.b];
        binoMask[colR][row] = !!b0;
      }
      if (colL >= 0 && colL < WABE_W && row >= 0 && row < WABE_H) {
        wabe[colL][row]     = [c1.r, c1.g, c1.b];
        binoMask[colL][row] = !!b1;
      }
      if (colR >= 0 && colR < WABE_W && rowN >= 0 && rowN < WABE_H) {
        wabe[colR][rowN]     = [c2.r, c2.g, c2.b];
        binoMask[colR][rowN] = !!b2;
      }
      if (colL >= 0 && colL < WABE_W && rowN >= 0 && rowN < WABE_H) {
        wabe[colL][rowN]     = [c3.r, c3.g, c3.b];
        binoMask[colL][rowN] = !!b3;
      }

      if (i + 4 < this.nromm && this.omm[i + 4].x < this.omm[i].x) {
        wx = 0; wy++;
        odd = odd === 1 ? 0 : 1;
      } else {
        wx++;
      }
    }
    return { wabe, binoMask };
  }

  /**
   * Draw one eye's hex mosaic into a horizontal sub-region of the canvas.
   * x0..x0+w spans this eye's portion of the canvas; vertical fills the full
   * canvas height.  +y ommatidia (looking up) draw at the TOP.
   */
  _drawEyeHexes(eye, x0, w) {
    const ctx = this.ctx;
    const H   = this.canvas.height;
    const WABE_W = 60, WABE_H = 160;
    const { wabe, binoMask } = this._buildWabe(eye, WABE_W, WABE_H);

    const cellW = w / WABE_W;
    const cellH = H / WABE_H;
    const r     = Math.max(cellW, cellH) * 0.85;
    const bRGB  = this.brightness;
    const showB = this.showBinocular;
    // Outline thickness scales with cell size, capped so it doesn't dominate
    const strokeW = Math.max(0.6, Math.min(1.4, r * 0.18));

    for (let j = 0; j < WABE_H; j++) {
      const yPx  = (WABE_H - 1 - j) * cellH + cellH * 0.5;
      const offX = (j % 2 === 1) ? cellW * 0.5 : 0;
      for (let i = 0; i < WABE_W; i++) {
        const c = wabe[i][j];
        if (c === null) continue; // skip cells that no ommatidium covers
        const cr = Math.max(0, Math.min(255, Math.round(c[0] * bRGB)));
        const cg = Math.max(0, Math.min(255, Math.round(c[1] * bRGB)));
        const cb = Math.max(0, Math.min(255, Math.round(c[2] * bRGB)));
        const xPx = x0 + i * cellW + offX + cellW * 0.5;
        ctx.fillStyle = `rgb(${cr},${cg},${cb})`;
        ctx.beginPath();
        ctx.arc(xPx, yPx, r, 0, Math.PI * 2);
        ctx.fill();
        if (showB && binoMask[i][j]) {
          ctx.lineWidth   = strokeW;
          ctx.strokeStyle = 'rgba(255, 230, 80, 0.9)';
          ctx.stroke();
        }
      }
    }
  }

  // ── DispHex: draw both eyes side-by-side ─────────────────────────────────
  _dispHex() {
    if (!this.ctx || !this.canvas) return;
    const W = this.canvas.width;
    const H = this.canvas.height;
    const ctx = this.ctx;

    // Near-black background (gaps read as inter-ommatidial dark space)
    ctx.fillStyle = `rgb(${EMPTY_CELL[0]},${EMPTY_CELL[1]},${EMPTY_CELL[2]})`;
    ctx.fillRect(0, 0, W, H);

    const halfW = W * 0.5;
    // Left eye on left half, right eye on right half
    this._drawEyeHexes(this.eyes[0], 0,     halfW);
    this._drawEyeHexes(this.eyes[1], halfW, halfW);

    // Subtle vertical divider between the two eyes
    ctx.strokeStyle = 'rgba(255,255,255,0.06)';
    ctx.lineWidth   = 1;
    ctx.beginPath();
    ctx.moveTo(halfW + 0.5, 0);
    ctx.lineTo(halfW + 0.5, H);
    ctx.stroke();
  }

  /**
   * Main render call (called from Viewport each frame).
   *
   * @param {THREE.WebGLRenderer} renderer
   * @param {THREE.Scene}         scene
   * @param {THREE.Vector3}       headPosition  – world-space bee head position
   * @param {number}              headYaw       – head yaw in radians (bodyYaw + headYaw)
   * @param {THREE.Object3D}      [beeMesh]     – hidden during render so the
   *                                              bee doesn't occlude its own view
   */
  render(renderer, scene, headPosition, headYaw, beeMesh) {
    if (!scene || !renderer || !headPosition) return;

    // Mobile frame-skip: only re-render the compound eye every Nth frame.
    // The canvas retains its last painted frame in between, so the mosaic
    // stays visible — it just updates less often (~10 fps on mobile).
    this._eyeFrameCounter = (this._eyeFrameCounter + 1) % EYE_FRAME_SKIP;
    if (this._eyeFrameCounter !== 0) return;

    // 1. Hide bee model
    let prevVis = true;
    if (beeMesh) { prevVis = beeMesh.visible; beeMesh.visible = false; }

    // 2. Render the 6 faces
    const prevTarget = renderer.getRenderTarget();
    for (let face = 0; face < 6; face++) {
      const cam = this.faceCams[face];
      const def = FACE_DEFS[face];
      cam.position.copy(headPosition);
      cam.up.set(def.up[0], def.up[1], def.up[2]);
      this._tmpTarget.set(
        headPosition.x + def.fwd[0],
        headPosition.y + def.fwd[1],
        headPosition.z + def.fwd[2],
      );
      cam.lookAt(this._tmpTarget);
      renderer.setRenderTarget(this.faceTargets[face]);
      renderer.render(scene, cam);
    }
    renderer.setRenderTarget(prevTarget);

    if (beeMesh) beeMesh.visible = prevVis;

    // 3. Read each face buffer back to CPU
    for (let face = 0; face < 6; face++) {
      renderer.readRenderTargetPixels(
        this.faceTargets[face], 0, 0, FACE_SIZE, FACE_SIZE,
        this.facePixels[face],
      );
    }

    // 4. Sample each eye's ommatidia
    this._procPatEye(this.eyes[0], headYaw);
    this._procPatEye(this.eyes[1], headYaw);

    // 5. Draw the dual hex mosaic
    this._dispHex();
  }

  dispose() {
    for (const t of this.faceTargets) t.dispose();
  }
}
